---
apiVersion: v1
kind: Service
metadata:
  name: conjur-postgres
  labels:
    app: conjur-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: conjur-postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-postgres
  labels:
    app: conjur-postgres
spec:
  selector:
    matchLabels:
      app: conjur-postgres
      name: conjur-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-postgres
        name: conjur-postgres
    spec:
      containers:
      - image: postgres:10.1
        # image: {{ POSTGRES_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: postgres
